// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_cQTWhdbWcoNly-wXloTN4KUTndyIX0',
    appId: '1:104125112978:android:3e3f1344f371dc76d93c4b',
    messagingSenderId: '104125112978',
    projectId: 'safe-sphere-16d18',
    storageBucket: 'safe-sphere-16d18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpsoKFY9Zdwo28XFdu4aoV7WwE9lym7Ro',
    appId: '1:104125112978:ios:bc352de5f64395abd93c4b',
    messagingSenderId: '104125112978',
    projectId: 'safe-sphere-16d18',
    storageBucket: 'safe-sphere-16d18.appspot.com',
    androidClientId: '104125112978-gj7qrqdf1dd1t0k38cfl3bu2v02d076i.apps.googleusercontent.com',
    iosClientId: '104125112978-as0104qe5q1kq80v4u5bhp4ur5gs5t4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.safesphere',
  );
}
